var namespaceqpid_1_1messaging =
[
    [ "Address", "classqpid_1_1messaging_1_1Address.html", "classqpid_1_1messaging_1_1Address" ],
    [ "PrivateImplRef", "classqpid_1_1messaging_1_1PrivateImplRef.html", null ],
    [ "Connection", "classqpid_1_1messaging_1_1Connection.html", "classqpid_1_1messaging_1_1Connection" ],
    [ "Duration", "classqpid_1_1messaging_1_1Duration.html", "classqpid_1_1messaging_1_1Duration" ],
    [ "MessagingException", "structqpid_1_1messaging_1_1MessagingException.html", "structqpid_1_1messaging_1_1MessagingException" ],
    [ "InvalidOptionString", "structqpid_1_1messaging_1_1InvalidOptionString.html", "structqpid_1_1messaging_1_1InvalidOptionString" ],
    [ "KeyError", "structqpid_1_1messaging_1_1KeyError.html", "structqpid_1_1messaging_1_1KeyError" ],
    [ "LinkError", "structqpid_1_1messaging_1_1LinkError.html", "structqpid_1_1messaging_1_1LinkError" ],
    [ "AddressError", "structqpid_1_1messaging_1_1AddressError.html", "structqpid_1_1messaging_1_1AddressError" ],
    [ "ResolutionError", "structqpid_1_1messaging_1_1ResolutionError.html", "structqpid_1_1messaging_1_1ResolutionError" ],
    [ "AssertionFailed", "structqpid_1_1messaging_1_1AssertionFailed.html", "structqpid_1_1messaging_1_1AssertionFailed" ],
    [ "NotFound", "structqpid_1_1messaging_1_1NotFound.html", "structqpid_1_1messaging_1_1NotFound" ],
    [ "MalformedAddress", "structqpid_1_1messaging_1_1MalformedAddress.html", "structqpid_1_1messaging_1_1MalformedAddress" ],
    [ "ReceiverError", "structqpid_1_1messaging_1_1ReceiverError.html", "structqpid_1_1messaging_1_1ReceiverError" ],
    [ "FetchError", "structqpid_1_1messaging_1_1FetchError.html", "structqpid_1_1messaging_1_1FetchError" ],
    [ "NoMessageAvailable", "structqpid_1_1messaging_1_1NoMessageAvailable.html", "structqpid_1_1messaging_1_1NoMessageAvailable" ],
    [ "SenderError", "structqpid_1_1messaging_1_1SenderError.html", "structqpid_1_1messaging_1_1SenderError" ],
    [ "SendError", "structqpid_1_1messaging_1_1SendError.html", "structqpid_1_1messaging_1_1SendError" ],
    [ "TargetCapacityExceeded", "structqpid_1_1messaging_1_1TargetCapacityExceeded.html", "structqpid_1_1messaging_1_1TargetCapacityExceeded" ],
    [ "SessionError", "structqpid_1_1messaging_1_1SessionError.html", "structqpid_1_1messaging_1_1SessionError" ],
    [ "SessionClosed", "structqpid_1_1messaging_1_1SessionClosed.html", "structqpid_1_1messaging_1_1SessionClosed" ],
    [ "TransactionError", "structqpid_1_1messaging_1_1TransactionError.html", "structqpid_1_1messaging_1_1TransactionError" ],
    [ "TransactionAborted", "structqpid_1_1messaging_1_1TransactionAborted.html", "structqpid_1_1messaging_1_1TransactionAborted" ],
    [ "UnauthorizedAccess", "structqpid_1_1messaging_1_1UnauthorizedAccess.html", "structqpid_1_1messaging_1_1UnauthorizedAccess" ],
    [ "ConnectionError", "structqpid_1_1messaging_1_1ConnectionError.html", "structqpid_1_1messaging_1_1ConnectionError" ],
    [ "TransportFailure", "structqpid_1_1messaging_1_1TransportFailure.html", "structqpid_1_1messaging_1_1TransportFailure" ],
    [ "FailoverUpdates", "classqpid_1_1messaging_1_1FailoverUpdates.html", "classqpid_1_1messaging_1_1FailoverUpdates" ],
    [ "Handle", "classqpid_1_1messaging_1_1Handle.html", "classqpid_1_1messaging_1_1Handle" ],
    [ "LoggerOutput", "classqpid_1_1messaging_1_1LoggerOutput.html", "classqpid_1_1messaging_1_1LoggerOutput" ],
    [ "Logger", "classqpid_1_1messaging_1_1Logger.html", null ],
    [ "Message", "classqpid_1_1messaging_1_1Message.html", "classqpid_1_1messaging_1_1Message" ],
    [ "EncodingException", "structqpid_1_1messaging_1_1EncodingException.html", "structqpid_1_1messaging_1_1EncodingException" ],
    [ "Receiver", "classqpid_1_1messaging_1_1Receiver.html", "classqpid_1_1messaging_1_1Receiver" ],
    [ "Sender", "classqpid_1_1messaging_1_1Sender.html", "classqpid_1_1messaging_1_1Sender" ],
    [ "Session", "classqpid_1_1messaging_1_1Session.html", "classqpid_1_1messaging_1_1Session" ]
];