#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import sys

from transom import *

site_url, input_dir, output_dir = sys.argv[1:4]

transom = Transom(site_url, input_dir, output_dir)
transom.init()

missing_files, extra_files = transom.check_output_files()

if extra_files != 0:
    print("Warning! {} extra files in the output".format(extra_files))

if missing_files == 0:
    print("PASSED")
else:
    print("FAILED")

sys.exit(missing_files)
