#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import os

from generate import *

def gen_dispatch_docs(release, source_dir, output_dir):
    build_dir = make_temp_dir()

    with working_dir(build_dir):
        call("cmake {}", source_dir)
        call("make")
        call("make docs")

    man_build_dir = join(build_dir, "docs", "man")

    for f in list_dir(man_build_dir, "*.html.in"):
        input_file = join(man_build_dir, f)
        output_file = join(output_dir, "man", f)

        copy(input_file, output_file)

    books_input_dir = join(source_dir, "docs", "books")
    book_input_file = join(books_input_dir, "user-guide", "book.adoc")
    book_output_dir = join(output_dir, "user-guide")
    book_output_file = join(book_output_dir, "index.html.in")

    remove(book_output_dir)
    make_dir(book_output_dir)

    call("asciidoctor --no-header-footer -o {} {}", book_output_file, book_input_file)
    copy(join(books_input_dir, "images"), join(book_output_dir, "images"))

    # Asciidoctor strips the title - add it back
    prepend(book_output_file, "<h1>Using Qpid Dispatch</h1>\n")

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = checkout_dir or fetch_source("dispatch", source_release)

gen_dispatch_docs(release, source_dir, release_dir)

notice("Docs generated")
