#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from generate import *

# API docs

def gen_api_doc(release, source_dir, release_dir):
    input_path = join(source_dir, "proton-j", "src", "main", "java")
    input_namespace = "org.apache.qpid.proton"
    output_dir = join(release_dir, "api")

    remove(output_dir)

    gen_javadoc(release=release,
                title="Qpid Proton-J API",
                input_paths=(input_path,),
                input_namespaces=(input_namespace,),
                output_dir=output_dir)

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = export_release_from_git("proton-j", source_release)

gen_api_doc(release, source_dir, release_dir)

notice("API documentation generated")
