#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from generate import *

def gen_dispatch_api_doc(release, source_dir, component_dir):
    include_dir = join(source_dir, "include")
    input_path = join(include_dir, "qpid", "dispatch")
    output_dir = join(component_dir, "api")

    gen_doxygen(release=release,
                title="Qpid Dispatch Library API",
                input_paths=(input_path,),
                strip_paths=(include_dir,),
                output_dir=output_dir)

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = export_release_from_git("dispatch", source_release)

gen_dispatch_api_doc(release, source_dir, release_dir)

notice("API documentation generated")
