#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from generate import *

def gen_protonj2_api(release, source_dir, release_dir):
    toplevel_pom = join(source_dir, "pom.xml")
    generated_docs = join(source_dir, "target/site/apidocs")
    modules = ".,protonj2,protonj2-client"
    output_dir = join(release_dir, "api")

    remove(output_dir)

    call("mvn -f {} clean javadoc:aggregate -Dnotimestamp -Dnoindex -pl '{}'", toplevel_pom, modules)

    copy(generated_docs, output_dir)

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = checkout_dir or fetch_source("protonj2", source_release)

gen_protonj2_api(release, source_dir, release_dir)

notice("Docs generated")
