#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from generate import *

def gen_jms_docs(release, source_dir, output_dir):
    docs_input_dir = join(source_dir, "qpid-jms-docs")
    docs_output_dir = join(output_dir, "docs")

    remove(docs_output_dir)

    copy(join(docs_input_dir, "Configuration.md"), join(docs_output_dir, "index.md"))

    copy(join(source_dir, "README.md"), join(output_dir, "building.md"))

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = checkout_dir or fetch_source("jms", source_release)

gen_jms_docs(release, source_dir, release_dir)

notice("Docs copied")
