#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

import os
from generate import *

def gen_books_and_man(release, source_dir, output_dir):
    build_dir = join(source_dir, "build")
    make_dir(build_dir)
    with working_dir(build_dir):
        call("cmake ..")
        call("make")
        call("make doc")

    build_doc = join(build_dir, "doc")

    # .html.in files are raw HTML bodies, the render script will apply the site style.
    for f in list_dir(build_doc, "*.html.in",  "*.pdf", "*.png"):
        if not f == "index.html.in": # Use gen-dispatch-release-page index.
            copy(join(build_doc, f), join(output_dir, f))

## Now do stuff ##
release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = checkout_dir or export_release_from_git("dispatch", source_release)

gen_books_and_man(release, source_dir, release_dir)

notice("Books generated")
