#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from generate import *

def gen_messaging_api(release, source_dir, release_dir):
    component_dir = join(release_dir, "messaging-api")
    remove(component_dir)

    input_path = join(source_dir, "python")
    input_namespace = "qpid.messaging"
    output_dir = join(component_dir, "api")

    gen_epydoc(release=release,
               title="Qpid Python Messaging API",
               input_paths=(input_path,),
               input_namespaces=(input_namespace,),
               output_dir=output_dir)

## Now do stuff ##

release, issues_release, source_release, release_dir, checkout_dir = setup_release_script()
source_dir = export_release_from_git("python", source_release)

gen_messaging_api(release, source_dir, release_dir)

notice("API documentation generated")
